### ISSUE TITLE
Text overflows button

### ISSUE THREAD

**Issue by RedCMD** [yannis300307/CasioDevTools#13]
not sure if its even possible to fix

if the window pane size is too small
the text on the button will overflow

![image](https://github.com/yannis300307/CasioDevTools/assets/33529441/b301e340-aae8-4a9c-bbb7-b9b0761a4425)
![image](https://github.com/yannis300307/CasioDevTools/assets/33529441/f0adece3-2d94-4b79-8400-4f4788e37e84)

**Comment by yannis300307** [comment]
Yes I can fix it by making the height of the button increasing on overflow or by setting up a minimum width for each button.

**Comment by yannis300307** [comment]
Thanks for reporting!
I've fixed it in feb993a91ba4258b6c941e79b9a5a2d1a8678c86
