### ISSUE TITLE
Prompt to install C++ extension is shown if extension is disabled

### ISSUE THREAD

**Issue by RedCMD** [yannis300307/CasioDevTools#15]
`C/C++ Extension is not installed on your system. Do you want to install it automaticaly?`
the prompt to install the C++ extension is shown even if the extension is already installed, but simply disabled

clicking `yes` says `C/C++ Extension has been installed !`
but the prompt will reappear if vscode is reloaded

you can put a dependency on it in `package.json`
```json
"extensionDependencies": [
	"ms-vscode.cpptools"
],
```

**Comment by yannis300307** [comment]
Thanks for reporting!
I fixed it in 6aaba785d84843b7702e0b664f15d3a41164ef5e
