### ISSUE TITLE
Error: `The sources has been built successfully!`

### ISSUE THREAD

**Issue by RedCMD** [yannis300307/CasioDevTools#17]
After clicking `Compile for FX`

A bunch of notifications popup with the last one saying `The sources has been built successfully!`
But the `.g1a` file doesn't exist and theres many errors in the console

same errors for CG

`Compiling for CG: -- The C compiler identification is unknown`
![image](https://github.com/yannis300307/CasioDevTools/assets/33529441/4cd859c1-abfa-4da3-91f1-651280d9f95b)

[vscode-app-1702108693118.log](https://github.com/yannis300307/CasioDevTools/files/13623298/vscode-app-1702108693118.log)

It was working a month ago
but after reinstalling fxsdk and gitea, it stopped

**Comment by yannis300307** [comment]
Thanks for reporting,
This error has been fixed in commit 739703027a196401f1589e249e0f86c9a588272a
